apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao-temp
  template:
    metadata: 
      labels:
        app: conversao-temp
    spec:
      containers: 
      - name: site
        image: sergiofdf/conversao-temperatura:v1
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: conversao-temp
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000
  type: NodePort